version: "3.8"

services:
  app:
    depends_on:
      - julia
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "3000:3000"
    environment:
      MIMIFUND_API_URL: http://julia:8000
      NEXT_PUBLIC_API_URL: http://localhost:3000/api
      NEXTAUTH_SECRET: SomeReallySecretString
      NEXTAUTH_URL: http://localhost:3000
      PORT: 3000
  julia:
    build:
      dockerfile: Dockerfile
      context: ./julia
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
