version: "3.8"

services:
  julia:
    build:
      dockerfile: Dockerfile
      context: ./julia
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
      - /app/src/styles
      - ./app:/app
    env_file:
      - ./app/.env
