version: "3.8"

services:
  web:
    depends_on:
      - mimi
    build:
      dockerfile: Dockerfile
      context: ./apps/web
    ports:
      - "3000:3000"
    environment:
      MIMIFUND_API_URL: http://mimi:8000
      NEXT_PUBLIC_API_URL: http://localhost:3000/api
      NEXTAUTH_SECRET: SomeReallySecretString
      NEXTAUTH_URL: http://localhost:3000
      PORT: 3000
  mimi:
    build:
      dockerfile: Dockerfile
      context: ./apps/mimi
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
