version: "3.8"

services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./apps/web
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_DATA_API_URL: api:4000
      PORT: 3000

  api:
    build:
      dockerfile: Dockerfile
      context: ./apps/data
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      AWS_DEFAULT_REGION: us-east-1
