version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    volumes:
      - /app/node_modules
      - /app/src/styles
      - ./app:/app
    env_file:
      - app/.env
    environment:
      - NODE_ENV=development
      - PORT=3000
  julia:
    build:
      dockerfile: Dockerfile
      context: ./julia
    environment:
      - NODE_ENV=production
      - PORT=5000
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 8080:80
    depends_on:
      - julia
      - app
