version: "3.8"

services:
  julia:
    build:
      dockerfile: Dockerfile
      context: ./julia
    environment:
      - NODE_ENV=production
      - PORT=5000
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    volumes:
      - /app/node_modules
      - /app/src/styles
      - ./app:/app
    env_file:
      - ./app/.env
