apiVersion: apps/v1
kind: Deployment
metadata:
  name: co2-pricing-julia-deployment
  labels:
    app: co2-pricing
    app.kubernetes.io/name: co2-pricing-julia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: co2-pricing
  template:
    metadata:
      labels:
        app: co2-pricing
        app.kubernetes.io/name: co2-pricing-app
    spec:
      containers:
        - name: co2-pricing-julia
          image: public.ecr.aws/openearthfoundation/co2-pricing-julia
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8000
              name: http-julia-port
          imagePullPolicy: "Always"
