apiVersion: apps/v1
kind: Deployment
metadata:
  name: co2-pricing-data-deployment
  labels:
    app: co2-pricing
    app.kubernetes.io/name: co2-pricing-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: co2-pricing
  template:
    metadata:
      labels:
        app: co2-pricing
        app.kubernetes.io/name: co2-pricing-data
    spec:
      containers:
        - name: co2-pricing-data
          image: public.ecr.aws/openearthfoundation/co2-pricing-data
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 4000
              name: http-data-port
          env:
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: PORT
              value: "4000"
          imagePullPolicy: "Always"
