apiVersion: v1
kind: Service
metadata:
  name: co2-pricing-app-service
spec:
  selector:
    app: co2-pricing
    app.kubernetes.io/name: co2-pricing-app
  ports:
    - name: co2-pricing-app-service-port
      protocol: TCP
      port: 3000
      targetPort: http-app-port
