apiVersion: v1
kind: Service
metadata:
  name: co2-pricing-data-service
spec:
  selector:
    app: co2-pricing
    app.kubernetes.io/name: co2-pricing-data
  ports:
    - name: co2-pricing-data-service-port
      protocol: TCP
      port: 4000
      targetPort: http-data-port
