name: 1. Validate CDK Pipelines

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: pipelines

jobs:
  validate: 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm-cache-typescript
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run build
      - run: cdk synth --context 'environment=dev'
