name: 2. Deploy CDK Pipelines

on:
  workflow_run:
    workflows: ["1. Validate CDK Pipelines"]
    types:
      - completed
    branches:
      - main
    pull_request:
      branches:
        - main
    

defaults:
  run:
    working-directory: pipelines

jobs:
  deploy_dev:
    runs-on: ubuntu-22.04
    environment: dev
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm-cache-typescript
      - run: pnpm install --frozen-lockfile
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: cdk bootstrap
      - run: cdk deploy --require-approval never --context 'environment=dev'

  deploy_staging:
    runs-on: ubuntu-22.04
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm-cache-typescript
      - run: pnpm install --frozen-lockfile
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: cdk bootstrap
      - run: cdk deploy --require-approval never --context 'environment=staging'

  deploy_production:
    runs-on: ubuntu-22.04
    environment: production
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm-cache-typescript
      - run: pnpm install --frozen-lockfile
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: cdk bootstrap
      - run: cdk deploy --require-approval never --context 'environment=production'