name: Push Data to ECR

on:
  push:
    paths:
      - apps/data/**
  pull_request:
    paths:
      - apps/data/**

jobs:
  pushToECR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Logging in to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/openearthfoundation

      - name: Pushing App to ECR
        env:
          VERSION: ${{ github.sha }}
          IMAGE: public.ecr.aws/openearthfoundation/co2-pricing-data

        run: |
          docker build -t $IMAGE:$VERSION apps/data
          docker tag $IMAGE:$VERSION $IMAGE:latest
          docker push $IMAGE:$VERSION
          docker push $IMAGE:latest
